### PR TITLE
Add what I've learned about the format

### PR DESCRIPTION
**Pull request by huw**
Thanks for this really helpful document!

I just wanted to quickly add the couple of things I've learned about the format while experimenting with it. While the note text looks like HTML (using the `<p>` tag for example), it uses quite a few custom XML tags, like `<run>`.

Also, I've added a quick bit of data about the `rank` value. I'm not sure how to generate these though, any ideas?

### CODE REVIEW

**Comment by huw** [comment]
Also, I'm not 100% sure about this because I haven't seen it in action, but the OmniFocus database has spaces for `altitude` and `radius` under Contexts for geofencing. I believe they'd be stored under the `<location>` tag. Do you have an iOS device you could try this with?

**Comment by tomzx** [comment]
Hello @huw,

Thanks for the PR. I've left a small comment, which once fixed, I'll merge into `2.0`.

I have no idea how the rank is particularly generated nor updated. My guess is that it will take a value relative to the item above/below it (thus +/- 1) and will then update any ranks accordingly.

Finally, I do not own an iOS device, so I cannot test the `altitude`/`radius` fields.

**Comment by huw** [comment]
Yeah, I think that may be how they're updated. My guess is that (if you look at my update) they convert to a simpler base 10 number before adding new ranks to the tree. But I guess we can't know for sure.

**Comment by tomzx** [comment]
It would probably be worth creating a new Omnifocus document and playing around with ordering to figure out what is really happening behind the scenes.

**Comment by huw** [comment]
I'm closing this to clear out my feed of open Pull Requests on GitHub

**Pull request closed without merging**
